inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - vendor/**

Documentation:
  Enabled: false

Encoding:
  Enabled: false

StringLiterals:
  Enabled: false

SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

MethodLength:
  Max: 20

SignalException:
  Enabled: False
