inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - vendor/**/*
  TargetRubyVersion: 2.3

Documentation:
  Enabled: false

Encoding:
  Enabled: false

StringLiterals:
  Enabled: false

SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

MethodLength:
  Max: 20

SignalException:
  Enabled: False

Style/EmptyLineAfterMagicComment:
  Enabled: False

Style/FileName:
  Exclude:
    - Appraisals

